name: habr news bot

on: push

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          echo "Building docker image"
          make build
